# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SwiftStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'

  # Pods for SwiftStudy

  target 'SwiftStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SwiftStudyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
